source "http://rubygems.org"

group :development do
  # uploader
  gem 'rake', '>= 12.3.3'
  gem 'jbundle', :github => 'mloughran/jbundle'
  gem 'aws-s3', '~> 0.6.0'
  gem 'httparty', '>= 0.21.0'
  # testing
  gem 'jasmine', '~> 2.0.0'
  # jasmine guard integration
  gem 'tilt'
  gem 'rb-fsevent', '~> 0.9.0'
  gem 'guard', '~> 2.2.4'
  gem 'guard-jasmine', '~> 1.18.3'
  gem 'guard-jshint-node', '~> 0.0.8'
  gem 'ruby-hmac', '~> 0.4.0'
end
